### ISSUE TITLE
SignalR-Client-Cpp in release mode asks for cpprest140d_2_7.dll 

### ISSUE THREAD

**Issue by tido64** [SignalR/SignalR-Client-Cpp#142]
```
>dumpbin /dependents Microsoft.AspNet.SignalR.Client.Cpp.v140.WinDesktop.1.0.0-beta1\build\native\dll\Win32\v140\Release\signalrclient.dll
Microsoft (R) COFF/PE Dumper Version 14.00.24215.1
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file Microsoft.AspNet.SignalR.Client.Cpp.v140.WinDesktop.1.0.0-beta1\build\native\dll\Win32\v140\Release\signalrclient.dll

File Type: DLL

  Image has the following dependencies:

    cpprest140d_2_7.dll
    KERNEL32.dll
    MSVCP140D.dll
    VCRUNTIME140D.dll
    ucrtbased.dll

  Summary

        C000 .data
       23000 .rdata
        B000 .reloc
        1000 .rsrc
       C1000 .text
        1000 .tls
```

I believe this is a regression of #127.

**Comment by moozzyk** [comment]
I am not seeing this - I just downloaded the package from NuGet:

```
PS C:\> dumpbin /dependents C:\Users\####\Downloads\microsoft.aspnet.signalr.client.cpp.v140.windesktop.1.0.0-beta1.nupkg\build\native\dll\Win3
2\v140\Release\signalrclient.dll
Microsoft (R) COFF/PE Dumper Version 14.00.24213.1
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file C:\Users\####\Downloads\microsoft.aspnet.signalr.client.cpp.v140.windesktop.1.0.0-beta1.nupkg\build\native\dll\Win32\v140\Release\signalrclient.dll

File Type: DLL

  Image has the following dependencies:

    cpprest140_2_7.dll
    KERNEL32.dll
    MSVCP140.dll
    VCRUNTIME140.dll
    api-ms-win-crt-runtime-l1-1-0.dll
    api-ms-win-crt-stdio-l1-1-0.dll
    api-ms-win-crt-string-l1-1-0.dll
    api-ms-win-crt-heap-l1-1-0.dll

  Summary

        C000 .data
       1C000 .rdata
        8000 .reloc
        1000 .rsrc
       56000 .text
        1000 .tls
```

(In fact I remember manually checking dependencies of each dll)

**Comment by tido64** [comment]
This is really weird. If I delete the packages folder and restore them in VS, it runs fine until next time I have to build. Then this happens again. I've never seen this before, maybe it's a NuGet/Visual Studio issue?

**Comment by moozzyk** [comment]
What configuration are you building? The package contains both debug and release version of dlls if you build debug then VS should copy debug versions to the output build folder if you build release then it should copy release versions. 

In the screenshot you provided you used: 
`dumpbin /dependents Microsoft.AspNet.SignalR.Client.Cpp.v140.WinDesktop.1.0.0-beta1\build\native\dll\Win32\v140\Release\signalrclient.dll`

Is this the path to the packages folder in your project? If yes, my understanding is that nothing is/should be touching these files once you restored packages for your project.

**Comment by tido64** [comment]
Indeed, that is the packages folder in my project. I've tried building for debug and release, x86 and x64. I can consistently reproduce this behaviour on the release builds. First build is okay. Second build sees the dlls replaced. I have to delete the packages folder for it to work again.

**Comment by moozzyk** [comment]
Thanks for reporting this. I was able to reproduce this and sent a PR with a fix (#143). If you want to work around this issue you can remove the same lines I removed from this file: `packages\Microsoft.AspNet.SignalR.Client.Cpp.v140.WinDesktop.1.0.0-beta1\build\native\Microsoft.AspNet.SignalR.Client.Cpp.v140.WinDesktop.targets` - just make sure you do this when you have correct dlls in the dll folder (i.e. you don't have debug versions in release folders).

**Comment by moozzyk** [comment]
Fixed in e1a914394b5a0fedca2f1be513f95c6262906d11

**Comment by tido64** [comment]
Thanks!

**Comment by tido64** [comment]
Have you made a new NuGet package with this fix? The current package is still broken.

**Comment by moozzyk** [comment]
No, there hasn't been a new SignalR release since this was fixed.
